/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;
import static java.lang.Thread.sleep;
import org.example.Words;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Joao
 */
public class Tela extends javax.swing.JFrame {
 
    
    private String texto;
    private int chave;
 
    /**
     * Creates new form tela
     */
    public Tela() {
        initComponents();
        foi();
    }
    
    private void foi(){

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelasenhas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        senha1 = new javax.swing.JTextField();
        senhaDesc = new javax.swing.JTextField();
        senha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Main");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Criptografar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 180, 50));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setText("Descriptografar");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 180, 50));

        tabelasenhas.setBackground(new java.awt.Color(0, 0, 0));
        tabelasenhas.setForeground(new java.awt.Color(45, 198, 34));
        tabelasenhas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ordem", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelasenhas.setAutoscrolls(false);
        tabelasenhas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tabelasenhas);
        if (tabelasenhas.getColumnModel().getColumnCount() > 0) {
            tabelasenhas.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 590, 180));

        jLabel2.setBackground(new java.awt.Color(104, 178, 235));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Chave:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        senha1.setBackground(new java.awt.Color(1, 0, 8));
        senha1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(senha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 110, 30));

        senhaDesc.setBackground(new java.awt.Color(1, 0, 8));
        senhaDesc.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        senhaDesc.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(senhaDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 530, 50));

        senha.setBackground(new java.awt.Color(1, 0, 8));
        senha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        senha.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 44, 530, 50));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Senha descriptografada");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Limpar campos");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 720, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/imgs/img criptografia.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, 790, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        
        
        Words w = new Words();
        texto = senha.getText();
        w.setTexto(texto);
        
        //descriptografando todas as senhas possiveis
        for (int j  = 1; j < 96; j++){
        
            String textoDescriptografado = w.decriptar(j, w.getTexto());
            System.out.println("TEXTO DESCRIPTOGRAFADO: " + textoDescriptografado);

            //adicionando na tabela
            DefaultTableModel dtmProdutos = (DefaultTableModel) tabelasenhas.getModel();
            Object[] dados = {j,textoDescriptografado};
            dtmProdutos.addRow(dados);
        }
        senha1.setText("");
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       
        Words w = new Words();
       
        chave = Integer.parseInt(senha1.getText());
        texto = senhaDesc.getText();
        
        String textoCriptografado = w.encriptar(chave, texto);
        
        senha.setText(textoCriptografado);
      
        

        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        senha1.setText("");
        senha.setText("");
        senhaDesc.setText("");
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField senha;
    private javax.swing.JTextField senha1;
    private javax.swing.JTextField senhaDesc;
    private javax.swing.JTable tabelasenhas;
    // End of variables declaration//GEN-END:variables
}
